#include <vulkan/vulkan.h>
namespace vkx {
constexpr auto ACCESS_COLOR_ATTACHMENT_READ_BIT =
    VK_ACCESS_COLOR_ATTACHMENT_READ_BIT;
constexpr auto ACCESS_COLOR_ATTACHMENT_WRITE_BIT =
    VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
constexpr auto ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT =
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT;
constexpr auto ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT =
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
constexpr auto ACCESS_HOST_READ_BIT = VK_ACCESS_HOST_READ_BIT;
constexpr auto ACCESS_HOST_WRITE_BIT = VK_ACCESS_HOST_WRITE_BIT;
constexpr auto ACCESS_INDEX_READ_BIT = VK_ACCESS_INDEX_READ_BIT;
constexpr auto ACCESS_INDIRECT_COMMAND_READ_BIT =
    VK_ACCESS_INDIRECT_COMMAND_READ_BIT;
constexpr auto ACCESS_INPUT_ATTACHMENT_READ_BIT =
    VK_ACCESS_INPUT_ATTACHMENT_READ_BIT;
constexpr auto ACCESS_MEMORY_READ_BIT = VK_ACCESS_MEMORY_READ_BIT;
constexpr auto ACCESS_MEMORY_WRITE_BIT = VK_ACCESS_MEMORY_WRITE_BIT;
constexpr auto ACCESS_SHADER_READ_BIT = VK_ACCESS_SHADER_READ_BIT;
constexpr auto ACCESS_SHADER_WRITE_BIT = VK_ACCESS_SHADER_WRITE_BIT;
constexpr auto ACCESS_TRANSFER_READ_BIT = VK_ACCESS_TRANSFER_READ_BIT;
constexpr auto ACCESS_TRANSFER_WRITE_BIT = VK_ACCESS_TRANSFER_WRITE_BIT;
constexpr auto ACCESS_UNIFORM_READ_BIT = VK_ACCESS_UNIFORM_READ_BIT;
constexpr auto ACCESS_VERTEX_ATTRIBUTE_READ_BIT =
    VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT;
constexpr auto ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT =
    VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT;
constexpr auto ATTACHMENT_LOAD_OP_CLEAR = VK_ATTACHMENT_LOAD_OP_CLEAR;
constexpr auto ATTACHMENT_LOAD_OP_DONT_CARE = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
constexpr auto ATTACHMENT_LOAD_OP_LOAD = VK_ATTACHMENT_LOAD_OP_LOAD;
constexpr auto ATTACHMENT_STORE_OP_DONT_CARE = VK_ATTACHMENT_STORE_OP_DONT_CARE;
constexpr auto ATTACHMENT_STORE_OP_STORE = VK_ATTACHMENT_STORE_OP_STORE;
constexpr auto ATTACHMENT_UNUSED = VK_ATTACHMENT_UNUSED;
constexpr auto BLEND_FACTOR_CONSTANT_ALPHA = VK_BLEND_FACTOR_CONSTANT_ALPHA;
constexpr auto BLEND_FACTOR_CONSTANT_COLOR = VK_BLEND_FACTOR_CONSTANT_COLOR;
constexpr auto BLEND_FACTOR_DST_ALPHA = VK_BLEND_FACTOR_DST_ALPHA;
constexpr auto BLEND_FACTOR_DST_COLOR = VK_BLEND_FACTOR_DST_COLOR;
constexpr auto BLEND_FACTOR_ONE = VK_BLEND_FACTOR_ONE;
constexpr auto BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA =
    VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA;
constexpr auto BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR =
    VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR;
constexpr auto BLEND_FACTOR_ONE_MINUS_DST_ALPHA =
    VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA;
constexpr auto BLEND_FACTOR_ONE_MINUS_DST_COLOR =
    VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR;
constexpr auto BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA =
    VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA;
constexpr auto BLEND_FACTOR_ONE_MINUS_SRC1_COLOR =
    VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR;
constexpr auto BLEND_FACTOR_ONE_MINUS_SRC_ALPHA =
    VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
constexpr auto BLEND_FACTOR_ONE_MINUS_SRC_COLOR =
    VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR;
constexpr auto BLEND_FACTOR_SRC1_ALPHA = VK_BLEND_FACTOR_SRC1_ALPHA;
constexpr auto BLEND_FACTOR_SRC1_COLOR = VK_BLEND_FACTOR_SRC1_COLOR;
constexpr auto BLEND_FACTOR_SRC_ALPHA = VK_BLEND_FACTOR_SRC_ALPHA;
constexpr auto BLEND_FACTOR_SRC_ALPHA_SATURATE =
    VK_BLEND_FACTOR_SRC_ALPHA_SATURATE;
constexpr auto BLEND_FACTOR_SRC_COLOR = VK_BLEND_FACTOR_SRC_COLOR;
constexpr auto BLEND_FACTOR_ZERO = VK_BLEND_FACTOR_ZERO;
constexpr auto BLEND_OP_ADD = VK_BLEND_OP_ADD;
constexpr auto BLEND_OP_MAX = VK_BLEND_OP_MAX;
constexpr auto BLEND_OP_MIN = VK_BLEND_OP_MIN;
constexpr auto BLEND_OP_REVERSE_SUBTRACT = VK_BLEND_OP_REVERSE_SUBTRACT;
constexpr auto BLEND_OP_SUBTRACT = VK_BLEND_OP_SUBTRACT;
constexpr auto BLEND_OVERLAP_CONJOINT_EXT = VK_BLEND_OVERLAP_CONJOINT_EXT;
constexpr auto BLEND_OVERLAP_DISJOINT_EXT = VK_BLEND_OVERLAP_DISJOINT_EXT;
constexpr auto BLEND_OVERLAP_UNCORRELATED_EXT =
    VK_BLEND_OVERLAP_UNCORRELATED_EXT;
constexpr auto BORDER_COLOR_FLOAT_OPAQUE_BLACK =
    VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK;
constexpr auto BORDER_COLOR_FLOAT_OPAQUE_WHITE =
    VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;
constexpr auto BORDER_COLOR_FLOAT_TRANSPARENT_BLACK =
    VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK;
constexpr auto BORDER_COLOR_INT_OPAQUE_BLACK = VK_BORDER_COLOR_INT_OPAQUE_BLACK;
constexpr auto BORDER_COLOR_INT_OPAQUE_WHITE = VK_BORDER_COLOR_INT_OPAQUE_WHITE;
constexpr auto BORDER_COLOR_INT_TRANSPARENT_BLACK =
    VK_BORDER_COLOR_INT_TRANSPARENT_BLACK;
constexpr auto BUFFER_CREATE_SPARSE_ALIASED_BIT =
    VK_BUFFER_CREATE_SPARSE_ALIASED_BIT;
constexpr auto BUFFER_CREATE_SPARSE_BINDING_BIT =
    VK_BUFFER_CREATE_SPARSE_BINDING_BIT;
constexpr auto BUFFER_CREATE_SPARSE_RESIDENCY_BIT =
    VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT;
constexpr auto BUFFER_USAGE_INDEX_BUFFER_BIT = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
constexpr auto BUFFER_USAGE_INDIRECT_BUFFER_BIT =
    VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT;
constexpr auto BUFFER_USAGE_STORAGE_BUFFER_BIT =
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
constexpr auto BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT =
    VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT;
constexpr auto BUFFER_USAGE_TRANSFER_DST_BIT = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
constexpr auto BUFFER_USAGE_TRANSFER_SRC_BIT = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
constexpr auto BUFFER_USAGE_UNIFORM_BUFFER_BIT =
    VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
constexpr auto BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT =
    VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT;
constexpr auto BUFFER_USAGE_VERTEX_BUFFER_BIT =
    VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
constexpr auto CHROMA_LOCATION_COSITED_EVEN = VK_CHROMA_LOCATION_COSITED_EVEN;
constexpr auto CHROMA_LOCATION_MIDPOINT = VK_CHROMA_LOCATION_MIDPOINT;
constexpr auto COLOR_COMPONENT_A_BIT = VK_COLOR_COMPONENT_A_BIT;
constexpr auto COLOR_COMPONENT_B_BIT = VK_COLOR_COMPONENT_B_BIT;
constexpr auto COLOR_COMPONENT_G_BIT = VK_COLOR_COMPONENT_G_BIT;
constexpr auto COLOR_COMPONENT_R_BIT = VK_COLOR_COMPONENT_R_BIT;
constexpr auto COLOR_SPACE_SRGB_NONLINEAR_KHR =
    VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
constexpr auto COMMAND_BUFFER_LEVEL_PRIMARY = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
constexpr auto COMMAND_BUFFER_LEVEL_SECONDARY =
    VK_COMMAND_BUFFER_LEVEL_SECONDARY;
constexpr auto COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT =
    VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT;
constexpr auto COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT =
    VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
constexpr auto COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT =
    VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT;
constexpr auto COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT =
    VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT;
constexpr auto COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT =
    VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
constexpr auto COMMAND_POOL_CREATE_TRANSIENT_BIT =
    VK_COMMAND_POOL_CREATE_TRANSIENT_BIT;
constexpr auto COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT =
    VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT;
constexpr auto COMPARE_OP_ALWAYS = VK_COMPARE_OP_ALWAYS;
constexpr auto COMPARE_OP_EQUAL = VK_COMPARE_OP_EQUAL;
constexpr auto COMPARE_OP_GREATER = VK_COMPARE_OP_GREATER;
constexpr auto COMPARE_OP_GREATER_OR_EQUAL = VK_COMPARE_OP_GREATER_OR_EQUAL;
constexpr auto COMPARE_OP_LESS = VK_COMPARE_OP_LESS;
constexpr auto COMPARE_OP_LESS_OR_EQUAL = VK_COMPARE_OP_LESS_OR_EQUAL;
constexpr auto COMPARE_OP_NEVER = VK_COMPARE_OP_NEVER;
constexpr auto COMPARE_OP_NOT_EQUAL = VK_COMPARE_OP_NOT_EQUAL;
constexpr auto COMPONENT_SWIZZLE_A = VK_COMPONENT_SWIZZLE_A;
constexpr auto COMPONENT_SWIZZLE_B = VK_COMPONENT_SWIZZLE_B;
constexpr auto COMPONENT_SWIZZLE_G = VK_COMPONENT_SWIZZLE_G;
constexpr auto COMPONENT_SWIZZLE_IDENTITY = VK_COMPONENT_SWIZZLE_IDENTITY;
constexpr auto COMPONENT_SWIZZLE_ONE = VK_COMPONENT_SWIZZLE_ONE;
constexpr auto COMPONENT_SWIZZLE_R = VK_COMPONENT_SWIZZLE_R;
constexpr auto COMPONENT_SWIZZLE_ZERO = VK_COMPONENT_SWIZZLE_ZERO;
constexpr auto COMPOSITE_ALPHA_INHERIT_BIT_KHR =
    VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR;
constexpr auto COMPOSITE_ALPHA_OPAQUE_BIT_KHR =
    VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
constexpr auto COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR =
    VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR;
constexpr auto COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR =
    VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR;
constexpr auto CONDITIONAL_RENDERING_INVERTED_BIT_EXT =
    VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT;
constexpr auto CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT =
    VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT;
constexpr auto CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT =
    VK_CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT;
constexpr auto CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT =
    VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT;
constexpr auto COVERAGE_MODULATION_MODE_ALPHA_NV =
    VK_COVERAGE_MODULATION_MODE_ALPHA_NV;
constexpr auto COVERAGE_MODULATION_MODE_NONE_NV =
    VK_COVERAGE_MODULATION_MODE_NONE_NV;
constexpr auto COVERAGE_MODULATION_MODE_RGBA_NV =
    VK_COVERAGE_MODULATION_MODE_RGBA_NV;
constexpr auto COVERAGE_MODULATION_MODE_RGB_NV =
    VK_COVERAGE_MODULATION_MODE_RGB_NV;
constexpr auto CULL_MODE_BACK_BIT = VK_CULL_MODE_BACK_BIT;
constexpr auto CULL_MODE_FRONT_AND_BACK = VK_CULL_MODE_FRONT_AND_BACK;
constexpr auto CULL_MODE_FRONT_BIT = VK_CULL_MODE_FRONT_BIT;
constexpr auto CULL_MODE_NONE = VK_CULL_MODE_NONE;
constexpr auto DEBUG_REPORT_DEBUG_BIT_EXT = VK_DEBUG_REPORT_DEBUG_BIT_EXT;
constexpr auto DEBUG_REPORT_ERROR_BIT_EXT = VK_DEBUG_REPORT_ERROR_BIT_EXT;
constexpr auto DEBUG_REPORT_INFORMATION_BIT_EXT =
    VK_DEBUG_REPORT_INFORMATION_BIT_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT;
constexpr auto DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT =
    VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT;
constexpr auto DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT =
    VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT;
constexpr auto DEBUG_REPORT_WARNING_BIT_EXT = VK_DEBUG_REPORT_WARNING_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT;
constexpr auto DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT =
    VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT;
constexpr auto DEPENDENCY_BY_REGION_BIT = VK_DEPENDENCY_BY_REGION_BIT;
constexpr auto DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT =
    VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT;
constexpr auto DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT =
    VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT;
constexpr auto DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT =
    VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT;
constexpr auto DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT =
    VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT;
constexpr auto DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT =
    VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
constexpr auto DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER =
    VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
constexpr auto DESCRIPTOR_TYPE_INPUT_ATTACHMENT =
    VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT;
constexpr auto DESCRIPTOR_TYPE_SAMPLED_IMAGE = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
constexpr auto DESCRIPTOR_TYPE_SAMPLER = VK_DESCRIPTOR_TYPE_SAMPLER;
constexpr auto DESCRIPTOR_TYPE_STORAGE_BUFFER =
    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
constexpr auto DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC =
    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC;
constexpr auto DESCRIPTOR_TYPE_STORAGE_IMAGE = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
constexpr auto DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER =
    VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER;
constexpr auto DESCRIPTOR_TYPE_UNIFORM_BUFFER =
    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
constexpr auto DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC =
    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
constexpr auto DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER =
    VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER;
constexpr auto DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET =
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET;
constexpr auto DEVICE_EVENT_TYPE_DISPLAY_HOTPLUG_EXT =
    VK_DEVICE_EVENT_TYPE_DISPLAY_HOTPLUG_EXT;
constexpr auto DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR =
    VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR;
constexpr auto DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR =
    VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR;
constexpr auto DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR =
    VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR;
constexpr auto DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR =
    VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR;
constexpr auto DISCARD_RECTANGLE_MODE_EXCLUSIVE_EXT =
    VK_DISCARD_RECTANGLE_MODE_EXCLUSIVE_EXT;
constexpr auto DISCARD_RECTANGLE_MODE_INCLUSIVE_EXT =
    VK_DISCARD_RECTANGLE_MODE_INCLUSIVE_EXT;
constexpr auto DISPLAY_EVENT_TYPE_FIRST_PIXEL_OUT_EXT =
    VK_DISPLAY_EVENT_TYPE_FIRST_PIXEL_OUT_EXT;
constexpr auto DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR =
    VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR;
constexpr auto DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR =
    VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR;
constexpr auto DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR =
    VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR;
constexpr auto DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR =
    VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR;
constexpr auto DISPLAY_POWER_STATE_OFF_EXT = VK_DISPLAY_POWER_STATE_OFF_EXT;
constexpr auto DISPLAY_POWER_STATE_ON_EXT = VK_DISPLAY_POWER_STATE_ON_EXT;
constexpr auto DISPLAY_POWER_STATE_SUSPEND_EXT =
    VK_DISPLAY_POWER_STATE_SUSPEND_EXT;
constexpr auto DYNAMIC_STATE_BLEND_CONSTANTS = VK_DYNAMIC_STATE_BLEND_CONSTANTS;
constexpr auto DYNAMIC_STATE_DEPTH_BIAS = VK_DYNAMIC_STATE_DEPTH_BIAS;
constexpr auto DYNAMIC_STATE_DEPTH_BOUNDS = VK_DYNAMIC_STATE_DEPTH_BOUNDS;
constexpr auto DYNAMIC_STATE_LINE_WIDTH = VK_DYNAMIC_STATE_LINE_WIDTH;
constexpr auto DYNAMIC_STATE_SCISSOR = VK_DYNAMIC_STATE_SCISSOR;
constexpr auto DYNAMIC_STATE_STENCIL_COMPARE_MASK =
    VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK;
constexpr auto DYNAMIC_STATE_STENCIL_REFERENCE =
    VK_DYNAMIC_STATE_STENCIL_REFERENCE;
constexpr auto DYNAMIC_STATE_STENCIL_WRITE_MASK =
    VK_DYNAMIC_STATE_STENCIL_WRITE_MASK;
constexpr auto DYNAMIC_STATE_VIEWPORT = VK_DYNAMIC_STATE_VIEWPORT;
constexpr auto ERROR_DEVICE_LOST = VK_ERROR_DEVICE_LOST;
constexpr auto ERROR_EXTENSION_NOT_PRESENT = VK_ERROR_EXTENSION_NOT_PRESENT;
constexpr auto ERROR_FEATURE_NOT_PRESENT = VK_ERROR_FEATURE_NOT_PRESENT;
constexpr auto ERROR_FORMAT_NOT_SUPPORTED = VK_ERROR_FORMAT_NOT_SUPPORTED;
constexpr auto ERROR_FRAGMENTED_POOL = VK_ERROR_FRAGMENTED_POOL;
constexpr auto ERROR_INCOMPATIBLE_DRIVER = VK_ERROR_INCOMPATIBLE_DRIVER;
constexpr auto ERROR_INITIALIZATION_FAILED = VK_ERROR_INITIALIZATION_FAILED;
constexpr auto ERROR_LAYER_NOT_PRESENT = VK_ERROR_LAYER_NOT_PRESENT;
constexpr auto ERROR_MEMORY_MAP_FAILED = VK_ERROR_MEMORY_MAP_FAILED;
constexpr auto ERROR_OUT_OF_DEVICE_MEMORY = VK_ERROR_OUT_OF_DEVICE_MEMORY;
constexpr auto ERROR_OUT_OF_HOST_MEMORY = VK_ERROR_OUT_OF_HOST_MEMORY;
constexpr auto ERROR_TOO_MANY_OBJECTS = VK_ERROR_TOO_MANY_OBJECTS;
constexpr auto EVENT_RESET = VK_EVENT_RESET;
constexpr auto EVENT_SET = VK_EVENT_SET;
constexpr auto EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT =
    VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT;
constexpr auto EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT =
    VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT;
constexpr auto EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT =
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT;
constexpr auto EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT =
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT;
constexpr auto EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT =
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT;
constexpr auto EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT =
    VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT;
constexpr auto EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT =
    VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT;
constexpr auto EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV =
    VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV;
constexpr auto EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT =
    VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT;
constexpr auto EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV =
    VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV;
constexpr auto EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT =
    VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT;
constexpr auto EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV =
    VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT;
constexpr auto EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV =
    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV;
constexpr auto EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT =
    VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT;
constexpr auto EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT =
    VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT;
constexpr auto EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT =
    VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT;
constexpr auto EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT =
    VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT;
constexpr auto EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT =
    VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT;
constexpr auto EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT =
    VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT;
constexpr auto EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT =
    VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT;
constexpr auto FALSE = VK_FALSE;
constexpr auto FENCE_CREATE_SIGNALED_BIT = VK_FENCE_CREATE_SIGNALED_BIT;
constexpr auto FENCE_IMPORT_TEMPORARY_BIT = VK_FENCE_IMPORT_TEMPORARY_BIT;
constexpr auto FILTER_LINEAR = VK_FILTER_LINEAR;
constexpr auto FILTER_NEAREST = VK_FILTER_NEAREST;
constexpr auto FORMAT_A1R5G5B5_UNORM_PACK16 = VK_FORMAT_A1R5G5B5_UNORM_PACK16;
constexpr auto FORMAT_A2B10G10R10_SINT_PACK32 =
    VK_FORMAT_A2B10G10R10_SINT_PACK32;
constexpr auto FORMAT_A2B10G10R10_SNORM_PACK32 =
    VK_FORMAT_A2B10G10R10_SNORM_PACK32;
constexpr auto FORMAT_A2B10G10R10_SSCALED_PACK32 =
    VK_FORMAT_A2B10G10R10_SSCALED_PACK32;
constexpr auto FORMAT_A2B10G10R10_UINT_PACK32 =
    VK_FORMAT_A2B10G10R10_UINT_PACK32;
constexpr auto FORMAT_A2B10G10R10_UNORM_PACK32 =
    VK_FORMAT_A2B10G10R10_UNORM_PACK32;
constexpr auto FORMAT_A2B10G10R10_USCALED_PACK32 =
    VK_FORMAT_A2B10G10R10_USCALED_PACK32;
constexpr auto FORMAT_A2R10G10B10_SINT_PACK32 =
    VK_FORMAT_A2R10G10B10_SINT_PACK32;
constexpr auto FORMAT_A2R10G10B10_SNORM_PACK32 =
    VK_FORMAT_A2R10G10B10_SNORM_PACK32;
constexpr auto FORMAT_A2R10G10B10_SSCALED_PACK32 =
    VK_FORMAT_A2R10G10B10_SSCALED_PACK32;
constexpr auto FORMAT_A2R10G10B10_UINT_PACK32 =
    VK_FORMAT_A2R10G10B10_UINT_PACK32;
constexpr auto FORMAT_A2R10G10B10_UNORM_PACK32 =
    VK_FORMAT_A2R10G10B10_UNORM_PACK32;
constexpr auto FORMAT_A2R10G10B10_USCALED_PACK32 =
    VK_FORMAT_A2R10G10B10_USCALED_PACK32;
constexpr auto FORMAT_A8B8G8R8_SINT_PACK32 = VK_FORMAT_A8B8G8R8_SINT_PACK32;
constexpr auto FORMAT_A8B8G8R8_SNORM_PACK32 = VK_FORMAT_A8B8G8R8_SNORM_PACK32;
constexpr auto FORMAT_A8B8G8R8_SRGB_PACK32 = VK_FORMAT_A8B8G8R8_SRGB_PACK32;
constexpr auto FORMAT_A8B8G8R8_SSCALED_PACK32 =
    VK_FORMAT_A8B8G8R8_SSCALED_PACK32;
constexpr auto FORMAT_A8B8G8R8_UINT_PACK32 = VK_FORMAT_A8B8G8R8_UINT_PACK32;
constexpr auto FORMAT_A8B8G8R8_UNORM_PACK32 = VK_FORMAT_A8B8G8R8_UNORM_PACK32;
constexpr auto FORMAT_A8B8G8R8_USCALED_PACK32 =
    VK_FORMAT_A8B8G8R8_USCALED_PACK32;
constexpr auto FORMAT_ASTC_10x10_SRGB_BLOCK = VK_FORMAT_ASTC_10x10_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_10x10_UNORM_BLOCK = VK_FORMAT_ASTC_10x10_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_10x5_SRGB_BLOCK = VK_FORMAT_ASTC_10x5_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_10x5_UNORM_BLOCK = VK_FORMAT_ASTC_10x5_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_10x6_SRGB_BLOCK = VK_FORMAT_ASTC_10x6_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_10x6_UNORM_BLOCK = VK_FORMAT_ASTC_10x6_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_10x8_SRGB_BLOCK = VK_FORMAT_ASTC_10x8_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_10x8_UNORM_BLOCK = VK_FORMAT_ASTC_10x8_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_12x10_SRGB_BLOCK = VK_FORMAT_ASTC_12x10_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_12x10_UNORM_BLOCK = VK_FORMAT_ASTC_12x10_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_12x12_SRGB_BLOCK = VK_FORMAT_ASTC_12x12_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_12x12_UNORM_BLOCK = VK_FORMAT_ASTC_12x12_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_4x4_SRGB_BLOCK = VK_FORMAT_ASTC_4x4_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_4x4_UNORM_BLOCK = VK_FORMAT_ASTC_4x4_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_5x4_SRGB_BLOCK = VK_FORMAT_ASTC_5x4_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_5x4_UNORM_BLOCK = VK_FORMAT_ASTC_5x4_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_5x5_SRGB_BLOCK = VK_FORMAT_ASTC_5x5_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_5x5_UNORM_BLOCK = VK_FORMAT_ASTC_5x5_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_6x5_SRGB_BLOCK = VK_FORMAT_ASTC_6x5_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_6x5_UNORM_BLOCK = VK_FORMAT_ASTC_6x5_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_6x6_SRGB_BLOCK = VK_FORMAT_ASTC_6x6_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_6x6_UNORM_BLOCK = VK_FORMAT_ASTC_6x6_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_8x5_SRGB_BLOCK = VK_FORMAT_ASTC_8x5_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_8x5_UNORM_BLOCK = VK_FORMAT_ASTC_8x5_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_8x6_SRGB_BLOCK = VK_FORMAT_ASTC_8x6_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_8x6_UNORM_BLOCK = VK_FORMAT_ASTC_8x6_UNORM_BLOCK;
constexpr auto FORMAT_ASTC_8x8_SRGB_BLOCK = VK_FORMAT_ASTC_8x8_SRGB_BLOCK;
constexpr auto FORMAT_ASTC_8x8_UNORM_BLOCK = VK_FORMAT_ASTC_8x8_UNORM_BLOCK;
constexpr auto FORMAT_B10G11R11_UFLOAT_PACK32 =
    VK_FORMAT_B10G11R11_UFLOAT_PACK32;
constexpr auto FORMAT_B4G4R4A4_UNORM_PACK16 = VK_FORMAT_B4G4R4A4_UNORM_PACK16;
constexpr auto FORMAT_B5G5R5A1_UNORM_PACK16 = VK_FORMAT_B5G5R5A1_UNORM_PACK16;
constexpr auto FORMAT_B5G6R5_UNORM_PACK16 = VK_FORMAT_B5G6R5_UNORM_PACK16;
constexpr auto FORMAT_B8G8R8A8_SINT = VK_FORMAT_B8G8R8A8_SINT;
constexpr auto FORMAT_B8G8R8A8_SNORM = VK_FORMAT_B8G8R8A8_SNORM;
constexpr auto FORMAT_B8G8R8A8_SRGB = VK_FORMAT_B8G8R8A8_SRGB;
constexpr auto FORMAT_B8G8R8A8_SSCALED = VK_FORMAT_B8G8R8A8_SSCALED;
constexpr auto FORMAT_B8G8R8A8_UINT = VK_FORMAT_B8G8R8A8_UINT;
constexpr auto FORMAT_B8G8R8A8_UNORM = VK_FORMAT_B8G8R8A8_UNORM;
constexpr auto FORMAT_B8G8R8A8_USCALED = VK_FORMAT_B8G8R8A8_USCALED;
constexpr auto FORMAT_B8G8R8_SINT = VK_FORMAT_B8G8R8_SINT;
constexpr auto FORMAT_B8G8R8_SNORM = VK_FORMAT_B8G8R8_SNORM;
constexpr auto FORMAT_B8G8R8_SRGB = VK_FORMAT_B8G8R8_SRGB;
constexpr auto FORMAT_B8G8R8_SSCALED = VK_FORMAT_B8G8R8_SSCALED;
constexpr auto FORMAT_B8G8R8_UINT = VK_FORMAT_B8G8R8_UINT;
constexpr auto FORMAT_B8G8R8_UNORM = VK_FORMAT_B8G8R8_UNORM;
constexpr auto FORMAT_B8G8R8_USCALED = VK_FORMAT_B8G8R8_USCALED;
constexpr auto FORMAT_BC1_RGBA_SRGB_BLOCK = VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
constexpr auto FORMAT_BC1_RGBA_UNORM_BLOCK = VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
constexpr auto FORMAT_BC1_RGB_SRGB_BLOCK = VK_FORMAT_BC1_RGB_SRGB_BLOCK;
constexpr auto FORMAT_BC1_RGB_UNORM_BLOCK = VK_FORMAT_BC1_RGB_UNORM_BLOCK;
constexpr auto FORMAT_BC2_SRGB_BLOCK = VK_FORMAT_BC2_SRGB_BLOCK;
constexpr auto FORMAT_BC2_UNORM_BLOCK = VK_FORMAT_BC2_UNORM_BLOCK;
constexpr auto FORMAT_BC3_SRGB_BLOCK = VK_FORMAT_BC3_SRGB_BLOCK;
constexpr auto FORMAT_BC3_UNORM_BLOCK = VK_FORMAT_BC3_UNORM_BLOCK;
constexpr auto FORMAT_BC4_SNORM_BLOCK = VK_FORMAT_BC4_SNORM_BLOCK;
constexpr auto FORMAT_BC4_UNORM_BLOCK = VK_FORMAT_BC4_UNORM_BLOCK;
constexpr auto FORMAT_BC5_SNORM_BLOCK = VK_FORMAT_BC5_SNORM_BLOCK;
constexpr auto FORMAT_BC5_UNORM_BLOCK = VK_FORMAT_BC5_UNORM_BLOCK;
constexpr auto FORMAT_BC6H_SFLOAT_BLOCK = VK_FORMAT_BC6H_SFLOAT_BLOCK;
constexpr auto FORMAT_BC6H_UFLOAT_BLOCK = VK_FORMAT_BC6H_UFLOAT_BLOCK;
constexpr auto FORMAT_BC7_SRGB_BLOCK = VK_FORMAT_BC7_SRGB_BLOCK;
constexpr auto FORMAT_BC7_UNORM_BLOCK = VK_FORMAT_BC7_UNORM_BLOCK;
constexpr auto FORMAT_D16_UNORM = VK_FORMAT_D16_UNORM;
constexpr auto FORMAT_D16_UNORM_S8_UINT = VK_FORMAT_D16_UNORM_S8_UINT;
constexpr auto FORMAT_D24_UNORM_S8_UINT = VK_FORMAT_D24_UNORM_S8_UINT;
constexpr auto FORMAT_D32_SFLOAT = VK_FORMAT_D32_SFLOAT;
constexpr auto FORMAT_D32_SFLOAT_S8_UINT = VK_FORMAT_D32_SFLOAT_S8_UINT;
constexpr auto FORMAT_E5B9G9R9_UFLOAT_PACK32 = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32;
constexpr auto FORMAT_EAC_R11G11_SNORM_BLOCK = VK_FORMAT_EAC_R11G11_SNORM_BLOCK;
constexpr auto FORMAT_EAC_R11G11_UNORM_BLOCK = VK_FORMAT_EAC_R11G11_UNORM_BLOCK;
constexpr auto FORMAT_EAC_R11_SNORM_BLOCK = VK_FORMAT_EAC_R11_SNORM_BLOCK;
constexpr auto FORMAT_EAC_R11_UNORM_BLOCK = VK_FORMAT_EAC_R11_UNORM_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK =
    VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK =
    VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK =
    VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK =
    VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8_SRGB_BLOCK = VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK;
constexpr auto FORMAT_ETC2_R8G8B8_UNORM_BLOCK =
    VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK;
constexpr auto FORMAT_FEATURE_BLIT_DST_BIT = VK_FORMAT_FEATURE_BLIT_DST_BIT;
constexpr auto FORMAT_FEATURE_BLIT_SRC_BIT = VK_FORMAT_FEATURE_BLIT_SRC_BIT;
constexpr auto FORMAT_FEATURE_COLOR_ATTACHMENT_BIT =
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT;
constexpr auto FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT =
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT;
constexpr auto FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT =
    VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT;
constexpr auto FORMAT_FEATURE_SAMPLED_IMAGE_BIT =
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT;
constexpr auto FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT =
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT;
constexpr auto FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT =
    VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT;
constexpr auto FORMAT_FEATURE_STORAGE_IMAGE_BIT =
    VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT;
constexpr auto FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT =
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT;
constexpr auto FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT =
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT;
constexpr auto FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT =
    VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT;
constexpr auto FORMAT_FEATURE_VERTEX_BUFFER_BIT =
    VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT;
constexpr auto FORMAT_R16G16B16A16_SFLOAT = VK_FORMAT_R16G16B16A16_SFLOAT;
constexpr auto FORMAT_R16G16B16A16_SINT = VK_FORMAT_R16G16B16A16_SINT;
constexpr auto FORMAT_R16G16B16A16_SNORM = VK_FORMAT_R16G16B16A16_SNORM;
constexpr auto FORMAT_R16G16B16A16_SSCALED = VK_FORMAT_R16G16B16A16_SSCALED;
constexpr auto FORMAT_R16G16B16A16_UINT = VK_FORMAT_R16G16B16A16_UINT;
constexpr auto FORMAT_R16G16B16A16_UNORM = VK_FORMAT_R16G16B16A16_UNORM;
constexpr auto FORMAT_R16G16B16A16_USCALED = VK_FORMAT_R16G16B16A16_USCALED;
constexpr auto FORMAT_R16G16B16_SFLOAT = VK_FORMAT_R16G16B16_SFLOAT;
constexpr auto FORMAT_R16G16B16_SINT = VK_FORMAT_R16G16B16_SINT;
constexpr auto FORMAT_R16G16B16_SNORM = VK_FORMAT_R16G16B16_SNORM;
constexpr auto FORMAT_R16G16B16_SSCALED = VK_FORMAT_R16G16B16_SSCALED;
constexpr auto FORMAT_R16G16B16_UINT = VK_FORMAT_R16G16B16_UINT;
constexpr auto FORMAT_R16G16B16_UNORM = VK_FORMAT_R16G16B16_UNORM;
constexpr auto FORMAT_R16G16B16_USCALED = VK_FORMAT_R16G16B16_USCALED;
constexpr auto FORMAT_R16G16_SFLOAT = VK_FORMAT_R16G16_SFLOAT;
constexpr auto FORMAT_R16G16_SINT = VK_FORMAT_R16G16_SINT;
constexpr auto FORMAT_R16G16_SNORM = VK_FORMAT_R16G16_SNORM;
constexpr auto FORMAT_R16G16_SSCALED = VK_FORMAT_R16G16_SSCALED;
constexpr auto FORMAT_R16G16_UINT = VK_FORMAT_R16G16_UINT;
constexpr auto FORMAT_R16G16_UNORM = VK_FORMAT_R16G16_UNORM;
constexpr auto FORMAT_R16G16_USCALED = VK_FORMAT_R16G16_USCALED;
constexpr auto FORMAT_R16_SFLOAT = VK_FORMAT_R16_SFLOAT;
constexpr auto FORMAT_R16_SINT = VK_FORMAT_R16_SINT;
constexpr auto FORMAT_R16_SNORM = VK_FORMAT_R16_SNORM;
constexpr auto FORMAT_R16_SSCALED = VK_FORMAT_R16_SSCALED;
constexpr auto FORMAT_R16_UINT = VK_FORMAT_R16_UINT;
constexpr auto FORMAT_R16_UNORM = VK_FORMAT_R16_UNORM;
constexpr auto FORMAT_R16_USCALED = VK_FORMAT_R16_USCALED;
constexpr auto FORMAT_R32G32B32A32_SFLOAT = VK_FORMAT_R32G32B32A32_SFLOAT;
constexpr auto FORMAT_R32G32B32A32_SINT = VK_FORMAT_R32G32B32A32_SINT;
constexpr auto FORMAT_R32G32B32A32_UINT = VK_FORMAT_R32G32B32A32_UINT;
constexpr auto FORMAT_R32G32B32_SFLOAT = VK_FORMAT_R32G32B32_SFLOAT;
constexpr auto FORMAT_R32G32B32_SINT = VK_FORMAT_R32G32B32_SINT;
constexpr auto FORMAT_R32G32B32_UINT = VK_FORMAT_R32G32B32_UINT;
constexpr auto FORMAT_R32G32_SFLOAT = VK_FORMAT_R32G32_SFLOAT;
constexpr auto FORMAT_R32G32_SINT = VK_FORMAT_R32G32_SINT;
constexpr auto FORMAT_R32G32_UINT = VK_FORMAT_R32G32_UINT;
constexpr auto FORMAT_R32_SFLOAT = VK_FORMAT_R32_SFLOAT;
constexpr auto FORMAT_R32_SINT = VK_FORMAT_R32_SINT;
constexpr auto FORMAT_R32_UINT = VK_FORMAT_R32_UINT;
constexpr auto FORMAT_R4G4B4A4_UNORM_PACK16 = VK_FORMAT_R4G4B4A4_UNORM_PACK16;
constexpr auto FORMAT_R4G4_UNORM_PACK8 = VK_FORMAT_R4G4_UNORM_PACK8;
constexpr auto FORMAT_R5G5B5A1_UNORM_PACK16 = VK_FORMAT_R5G5B5A1_UNORM_PACK16;
constexpr auto FORMAT_R5G6B5_UNORM_PACK16 = VK_FORMAT_R5G6B5_UNORM_PACK16;
constexpr auto FORMAT_R64G64B64A64_SFLOAT = VK_FORMAT_R64G64B64A64_SFLOAT;
constexpr auto FORMAT_R64G64B64A64_SINT = VK_FORMAT_R64G64B64A64_SINT;
constexpr auto FORMAT_R64G64B64A64_UINT = VK_FORMAT_R64G64B64A64_UINT;
constexpr auto FORMAT_R64G64B64_SFLOAT = VK_FORMAT_R64G64B64_SFLOAT;
constexpr auto FORMAT_R64G64B64_SINT = VK_FORMAT_R64G64B64_SINT;
constexpr auto FORMAT_R64G64B64_UINT = VK_FORMAT_R64G64B64_UINT;
constexpr auto FORMAT_R64G64_SFLOAT = VK_FORMAT_R64G64_SFLOAT;
constexpr auto FORMAT_R64G64_SINT = VK_FORMAT_R64G64_SINT;
constexpr auto FORMAT_R64G64_UINT = VK_FORMAT_R64G64_UINT;
constexpr auto FORMAT_R64_SFLOAT = VK_FORMAT_R64_SFLOAT;
constexpr auto FORMAT_R64_SINT = VK_FORMAT_R64_SINT;
constexpr auto FORMAT_R64_UINT = VK_FORMAT_R64_UINT;
constexpr auto FORMAT_R8G8B8A8_SINT = VK_FORMAT_R8G8B8A8_SINT;
constexpr auto FORMAT_R8G8B8A8_SNORM = VK_FORMAT_R8G8B8A8_SNORM;
constexpr auto FORMAT_R8G8B8A8_SRGB = VK_FORMAT_R8G8B8A8_SRGB;
constexpr auto FORMAT_R8G8B8A8_SSCALED = VK_FORMAT_R8G8B8A8_SSCALED;
constexpr auto FORMAT_R8G8B8A8_UINT = VK_FORMAT_R8G8B8A8_UINT;
constexpr auto FORMAT_R8G8B8A8_UNORM = VK_FORMAT_R8G8B8A8_UNORM;
constexpr auto FORMAT_R8G8B8A8_USCALED = VK_FORMAT_R8G8B8A8_USCALED;
constexpr auto FORMAT_R8G8B8_SINT = VK_FORMAT_R8G8B8_SINT;
constexpr auto FORMAT_R8G8B8_SNORM = VK_FORMAT_R8G8B8_SNORM;
constexpr auto FORMAT_R8G8B8_SRGB = VK_FORMAT_R8G8B8_SRGB;
constexpr auto FORMAT_R8G8B8_SSCALED = VK_FORMAT_R8G8B8_SSCALED;
constexpr auto FORMAT_R8G8B8_UINT = VK_FORMAT_R8G8B8_UINT;
constexpr auto FORMAT_R8G8B8_UNORM = VK_FORMAT_R8G8B8_UNORM;
constexpr auto FORMAT_R8G8B8_USCALED = VK_FORMAT_R8G8B8_USCALED;
constexpr auto FORMAT_R8G8_SINT = VK_FORMAT_R8G8_SINT;
constexpr auto FORMAT_R8G8_SNORM = VK_FORMAT_R8G8_SNORM;
constexpr auto FORMAT_R8G8_SRGB = VK_FORMAT_R8G8_SRGB;
constexpr auto FORMAT_R8G8_SSCALED = VK_FORMAT_R8G8_SSCALED;
constexpr auto FORMAT_R8G8_UINT = VK_FORMAT_R8G8_UINT;
constexpr auto FORMAT_R8G8_UNORM = VK_FORMAT_R8G8_UNORM;
constexpr auto FORMAT_R8G8_USCALED = VK_FORMAT_R8G8_USCALED;
constexpr auto FORMAT_R8_SINT = VK_FORMAT_R8_SINT;
constexpr auto FORMAT_R8_SNORM = VK_FORMAT_R8_SNORM;
constexpr auto FORMAT_R8_SRGB = VK_FORMAT_R8_SRGB;
constexpr auto FORMAT_R8_SSCALED = VK_FORMAT_R8_SSCALED;
constexpr auto FORMAT_R8_UINT = VK_FORMAT_R8_UINT;
constexpr auto FORMAT_R8_UNORM = VK_FORMAT_R8_UNORM;
constexpr auto FORMAT_R8_USCALED = VK_FORMAT_R8_USCALED;
constexpr auto FORMAT_S8_UINT = VK_FORMAT_S8_UINT;
constexpr auto FORMAT_UNDEFINED = VK_FORMAT_UNDEFINED;
constexpr auto FORMAT_X8_D24_UNORM_PACK32 = VK_FORMAT_X8_D24_UNORM_PACK32;
constexpr auto FRONT_FACE_CLOCKWISE = VK_FRONT_FACE_CLOCKWISE;
constexpr auto FRONT_FACE_COUNTER_CLOCKWISE = VK_FRONT_FACE_COUNTER_CLOCKWISE;
constexpr auto IMAGE_ASPECT_COLOR_BIT = VK_IMAGE_ASPECT_COLOR_BIT;
constexpr auto IMAGE_ASPECT_DEPTH_BIT = VK_IMAGE_ASPECT_DEPTH_BIT;
constexpr auto IMAGE_ASPECT_METADATA_BIT = VK_IMAGE_ASPECT_METADATA_BIT;
constexpr auto IMAGE_ASPECT_STENCIL_BIT = VK_IMAGE_ASPECT_STENCIL_BIT;
constexpr auto IMAGE_CREATE_CUBE_COMPATIBLE_BIT =
    VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
constexpr auto IMAGE_CREATE_MUTABLE_FORMAT_BIT =
    VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT;
constexpr auto IMAGE_CREATE_SPARSE_ALIASED_BIT =
    VK_IMAGE_CREATE_SPARSE_ALIASED_BIT;
constexpr auto IMAGE_CREATE_SPARSE_BINDING_BIT =
    VK_IMAGE_CREATE_SPARSE_BINDING_BIT;
constexpr auto IMAGE_CREATE_SPARSE_RESIDENCY_BIT =
    VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT;
constexpr auto IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL =
    VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
constexpr auto IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL =
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
constexpr auto IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL =
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
constexpr auto IMAGE_LAYOUT_GENERAL = VK_IMAGE_LAYOUT_GENERAL;
constexpr auto IMAGE_LAYOUT_PREINITIALIZED = VK_IMAGE_LAYOUT_PREINITIALIZED;
constexpr auto IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL =
    VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
constexpr auto IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL =
    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
constexpr auto IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL =
    VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
constexpr auto IMAGE_LAYOUT_UNDEFINED = VK_IMAGE_LAYOUT_UNDEFINED;
constexpr auto IMAGE_TILING_LINEAR = VK_IMAGE_TILING_LINEAR;
constexpr auto IMAGE_TILING_OPTIMAL = VK_IMAGE_TILING_OPTIMAL;
constexpr auto IMAGE_TYPE_1D = VK_IMAGE_TYPE_1D;
constexpr auto IMAGE_TYPE_2D = VK_IMAGE_TYPE_2D;
constexpr auto IMAGE_TYPE_3D = VK_IMAGE_TYPE_3D;
constexpr auto IMAGE_USAGE_COLOR_ATTACHMENT_BIT =
    VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
constexpr auto IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT =
    VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
constexpr auto IMAGE_USAGE_INPUT_ATTACHMENT_BIT =
    VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT;
constexpr auto IMAGE_USAGE_SAMPLED_BIT = VK_IMAGE_USAGE_SAMPLED_BIT;
constexpr auto IMAGE_USAGE_STORAGE_BIT = VK_IMAGE_USAGE_STORAGE_BIT;
constexpr auto IMAGE_USAGE_TRANSFER_DST_BIT = VK_IMAGE_USAGE_TRANSFER_DST_BIT;
constexpr auto IMAGE_USAGE_TRANSFER_SRC_BIT = VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
constexpr auto IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT =
    VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT;
constexpr auto IMAGE_VIEW_TYPE_1D = VK_IMAGE_VIEW_TYPE_1D;
constexpr auto IMAGE_VIEW_TYPE_1D_ARRAY = VK_IMAGE_VIEW_TYPE_1D_ARRAY;
constexpr auto IMAGE_VIEW_TYPE_2D = VK_IMAGE_VIEW_TYPE_2D;
constexpr auto IMAGE_VIEW_TYPE_2D_ARRAY = VK_IMAGE_VIEW_TYPE_2D_ARRAY;
constexpr auto IMAGE_VIEW_TYPE_3D = VK_IMAGE_VIEW_TYPE_3D;
constexpr auto IMAGE_VIEW_TYPE_CUBE = VK_IMAGE_VIEW_TYPE_CUBE;
constexpr auto IMAGE_VIEW_TYPE_CUBE_ARRAY = VK_IMAGE_VIEW_TYPE_CUBE_ARRAY;
constexpr auto INCOMPLETE = VK_INCOMPLETE;
constexpr auto INDEX_TYPE_UINT16 = VK_INDEX_TYPE_UINT16;
constexpr auto INDEX_TYPE_UINT32 = VK_INDEX_TYPE_UINT32;
constexpr auto INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX =
    VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX;
constexpr auto INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX =
    VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX;
constexpr auto INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX =
    VK_INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX;
constexpr auto INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX =
    VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_DESCRIPTOR_SET_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_DESCRIPTOR_SET_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NVX;
constexpr auto INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NVX =
    VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NVX;
constexpr auto INTERNAL_ALLOCATION_TYPE_EXECUTABLE =
    VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE;
constexpr auto LOD_CLAMP_NONE = VK_LOD_CLAMP_NONE;
constexpr auto LOGIC_OP_AND = VK_LOGIC_OP_AND;
constexpr auto LOGIC_OP_AND_INVERTED = VK_LOGIC_OP_AND_INVERTED;
constexpr auto LOGIC_OP_AND_REVERSE = VK_LOGIC_OP_AND_REVERSE;
constexpr auto LOGIC_OP_CLEAR = VK_LOGIC_OP_CLEAR;
constexpr auto LOGIC_OP_COPY = VK_LOGIC_OP_COPY;
constexpr auto LOGIC_OP_COPY_INVERTED = VK_LOGIC_OP_COPY_INVERTED;
constexpr auto LOGIC_OP_EQUIVALENT = VK_LOGIC_OP_EQUIVALENT;
constexpr auto LOGIC_OP_INVERT = VK_LOGIC_OP_INVERT;
constexpr auto LOGIC_OP_NAND = VK_LOGIC_OP_NAND;
constexpr auto LOGIC_OP_NOR = VK_LOGIC_OP_NOR;
constexpr auto LOGIC_OP_NO_OP = VK_LOGIC_OP_NO_OP;
constexpr auto LOGIC_OP_OR = VK_LOGIC_OP_OR;
constexpr auto LOGIC_OP_OR_INVERTED = VK_LOGIC_OP_OR_INVERTED;
constexpr auto LOGIC_OP_OR_REVERSE = VK_LOGIC_OP_OR_REVERSE;
constexpr auto LOGIC_OP_SET = VK_LOGIC_OP_SET;
constexpr auto LOGIC_OP_XOR = VK_LOGIC_OP_XOR;
constexpr auto LUID_SIZE = VK_LUID_SIZE;
constexpr auto LUID_SIZE = VK_LUID_SIZE;
constexpr auto MAX_DESCRIPTION_SIZE = VK_MAX_DESCRIPTION_SIZE;
constexpr auto MAX_DEVICE_GROUP_SIZE = VK_MAX_DEVICE_GROUP_SIZE;
constexpr auto MAX_DEVICE_GROUP_SIZE = VK_MAX_DEVICE_GROUP_SIZE;
constexpr auto MAX_EXTENSION_NAME_SIZE = VK_MAX_EXTENSION_NAME_SIZE;
constexpr auto MAX_MEMORY_HEAPS = VK_MAX_MEMORY_HEAPS;
constexpr auto MAX_MEMORY_TYPES = VK_MAX_MEMORY_TYPES;
constexpr auto MAX_PHYSICAL_DEVICE_NAME_SIZE = VK_MAX_PHYSICAL_DEVICE_NAME_SIZE;
constexpr auto MEMORY_ALLOCATE_DEVICE_MASK_BIT =
    VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT;
constexpr auto MEMORY_HEAP_DEVICE_LOCAL_BIT = VK_MEMORY_HEAP_DEVICE_LOCAL_BIT;
constexpr auto MEMORY_PROPERTY_DEVICE_LOCAL_BIT =
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
constexpr auto MEMORY_PROPERTY_HOST_CACHED_BIT =
    VK_MEMORY_PROPERTY_HOST_CACHED_BIT;
constexpr auto MEMORY_PROPERTY_HOST_COHERENT_BIT =
    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
constexpr auto MEMORY_PROPERTY_HOST_VISIBLE_BIT =
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
constexpr auto MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT =
    VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT;
constexpr auto NOT_READY = VK_NOT_READY;
constexpr auto OBJECT_ENTRY_TYPE_DESCRIPTOR_SET_NVX =
    VK_OBJECT_ENTRY_TYPE_DESCRIPTOR_SET_NVX;
constexpr auto OBJECT_ENTRY_TYPE_INDEX_BUFFER_NVX =
    VK_OBJECT_ENTRY_TYPE_INDEX_BUFFER_NVX;
constexpr auto OBJECT_ENTRY_TYPE_PIPELINE_NVX =
    VK_OBJECT_ENTRY_TYPE_PIPELINE_NVX;
constexpr auto OBJECT_ENTRY_TYPE_PUSH_CONSTANT_NVX =
    VK_OBJECT_ENTRY_TYPE_PUSH_CONSTANT_NVX;
constexpr auto OBJECT_ENTRY_TYPE_VERTEX_BUFFER_NVX =
    VK_OBJECT_ENTRY_TYPE_VERTEX_BUFFER_NVX;
constexpr auto OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX =
    VK_OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX;
constexpr auto OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX =
    VK_OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX;
constexpr auto OBJECT_TYPE_BUFFER = VK_OBJECT_TYPE_BUFFER;
constexpr auto OBJECT_TYPE_BUFFER_VIEW = VK_OBJECT_TYPE_BUFFER_VIEW;
constexpr auto OBJECT_TYPE_COMMAND_BUFFER = VK_OBJECT_TYPE_COMMAND_BUFFER;
constexpr auto OBJECT_TYPE_COMMAND_POOL = VK_OBJECT_TYPE_COMMAND_POOL;
constexpr auto OBJECT_TYPE_DESCRIPTOR_POOL = VK_OBJECT_TYPE_DESCRIPTOR_POOL;
constexpr auto OBJECT_TYPE_DESCRIPTOR_SET = VK_OBJECT_TYPE_DESCRIPTOR_SET;
constexpr auto OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT =
    VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT;
constexpr auto OBJECT_TYPE_DEVICE = VK_OBJECT_TYPE_DEVICE;
constexpr auto OBJECT_TYPE_DEVICE_MEMORY = VK_OBJECT_TYPE_DEVICE_MEMORY;
constexpr auto OBJECT_TYPE_EVENT = VK_OBJECT_TYPE_EVENT;
constexpr auto OBJECT_TYPE_FENCE = VK_OBJECT_TYPE_FENCE;
constexpr auto OBJECT_TYPE_FRAMEBUFFER = VK_OBJECT_TYPE_FRAMEBUFFER;
constexpr auto OBJECT_TYPE_IMAGE = VK_OBJECT_TYPE_IMAGE;
constexpr auto OBJECT_TYPE_IMAGE_VIEW = VK_OBJECT_TYPE_IMAGE_VIEW;
constexpr auto OBJECT_TYPE_INSTANCE = VK_OBJECT_TYPE_INSTANCE;
constexpr auto OBJECT_TYPE_PHYSICAL_DEVICE = VK_OBJECT_TYPE_PHYSICAL_DEVICE;
constexpr auto OBJECT_TYPE_PIPELINE = VK_OBJECT_TYPE_PIPELINE;
constexpr auto OBJECT_TYPE_PIPELINE_CACHE = VK_OBJECT_TYPE_PIPELINE_CACHE;
constexpr auto OBJECT_TYPE_PIPELINE_LAYOUT = VK_OBJECT_TYPE_PIPELINE_LAYOUT;
constexpr auto OBJECT_TYPE_QUERY_POOL = VK_OBJECT_TYPE_QUERY_POOL;
constexpr auto OBJECT_TYPE_QUEUE = VK_OBJECT_TYPE_QUEUE;
constexpr auto OBJECT_TYPE_RENDER_PASS = VK_OBJECT_TYPE_RENDER_PASS;
constexpr auto OBJECT_TYPE_SAMPLER = VK_OBJECT_TYPE_SAMPLER;
constexpr auto OBJECT_TYPE_SEMAPHORE = VK_OBJECT_TYPE_SEMAPHORE;
constexpr auto OBJECT_TYPE_SHADER_MODULE = VK_OBJECT_TYPE_SHADER_MODULE;
constexpr auto OBJECT_TYPE_UNKNOWN = VK_OBJECT_TYPE_UNKNOWN;
constexpr auto PEER_MEMORY_FEATURE_COPY_DST_BIT =
    VK_PEER_MEMORY_FEATURE_COPY_DST_BIT;
constexpr auto PEER_MEMORY_FEATURE_COPY_SRC_BIT =
    VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT;
constexpr auto PEER_MEMORY_FEATURE_GENERIC_DST_BIT =
    VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT;
constexpr auto PEER_MEMORY_FEATURE_GENERIC_SRC_BIT =
    VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT;
constexpr auto PHYSICAL_DEVICE_TYPE_CPU = VK_PHYSICAL_DEVICE_TYPE_CPU;
constexpr auto PHYSICAL_DEVICE_TYPE_DISCRETE_GPU =
    VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU;
constexpr auto PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU =
    VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU;
constexpr auto PHYSICAL_DEVICE_TYPE_OTHER = VK_PHYSICAL_DEVICE_TYPE_OTHER;
constexpr auto PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU =
    VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU;
constexpr auto PIPELINE_BIND_POINT_COMPUTE = VK_PIPELINE_BIND_POINT_COMPUTE;
constexpr auto PIPELINE_BIND_POINT_GRAPHICS = VK_PIPELINE_BIND_POINT_GRAPHICS;
constexpr auto PIPELINE_CACHE_HEADER_VERSION_ONE =
    VK_PIPELINE_CACHE_HEADER_VERSION_ONE;
constexpr auto PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT =
    VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT;
constexpr auto PIPELINE_CREATE_DERIVATIVE_BIT =
    VK_PIPELINE_CREATE_DERIVATIVE_BIT;
constexpr auto PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT =
    VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT;
constexpr auto PIPELINE_STAGE_ALL_COMMANDS_BIT =
    VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
constexpr auto PIPELINE_STAGE_ALL_GRAPHICS_BIT =
    VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT;
constexpr auto PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT =
    VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
constexpr auto PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT =
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
constexpr auto PIPELINE_STAGE_COMPUTE_SHADER_BIT =
    VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;
constexpr auto PIPELINE_STAGE_DRAW_INDIRECT_BIT =
    VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT;
constexpr auto PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT =
    VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
constexpr auto PIPELINE_STAGE_FRAGMENT_SHADER_BIT =
    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
constexpr auto PIPELINE_STAGE_GEOMETRY_SHADER_BIT =
    VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT;
constexpr auto PIPELINE_STAGE_HOST_BIT = VK_PIPELINE_STAGE_HOST_BIT;
constexpr auto PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT =
    VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
constexpr auto PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT =
    VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT;
constexpr auto PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT =
    VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT;
constexpr auto PIPELINE_STAGE_TOP_OF_PIPE_BIT =
    VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
constexpr auto PIPELINE_STAGE_TRANSFER_BIT = VK_PIPELINE_STAGE_TRANSFER_BIT;
constexpr auto PIPELINE_STAGE_VERTEX_INPUT_BIT =
    VK_PIPELINE_STAGE_VERTEX_INPUT_BIT;
constexpr auto PIPELINE_STAGE_VERTEX_SHADER_BIT =
    VK_PIPELINE_STAGE_VERTEX_SHADER_BIT;
constexpr auto POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES =
    VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES;
constexpr auto POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY =
    VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY;
constexpr auto POLYGON_MODE_FILL = VK_POLYGON_MODE_FILL;
constexpr auto POLYGON_MODE_LINE = VK_POLYGON_MODE_LINE;
constexpr auto POLYGON_MODE_POINT = VK_POLYGON_MODE_POINT;
constexpr auto PRESENT_MODE_FIFO_KHR = VK_PRESENT_MODE_FIFO_KHR;
constexpr auto PRESENT_MODE_FIFO_RELAXED_KHR = VK_PRESENT_MODE_FIFO_RELAXED_KHR;
constexpr auto PRESENT_MODE_IMMEDIATE_KHR = VK_PRESENT_MODE_IMMEDIATE_KHR;
constexpr auto PRESENT_MODE_MAILBOX_KHR = VK_PRESENT_MODE_MAILBOX_KHR;
constexpr auto PRIMITIVE_TOPOLOGY_LINE_LIST = VK_PRIMITIVE_TOPOLOGY_LINE_LIST;
constexpr auto PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY =
    VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY;
constexpr auto PRIMITIVE_TOPOLOGY_LINE_STRIP = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP;
constexpr auto PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY =
    VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY;
constexpr auto PRIMITIVE_TOPOLOGY_PATCH_LIST = VK_PRIMITIVE_TOPOLOGY_PATCH_LIST;
constexpr auto PRIMITIVE_TOPOLOGY_POINT_LIST = VK_PRIMITIVE_TOPOLOGY_POINT_LIST;
constexpr auto PRIMITIVE_TOPOLOGY_TRIANGLE_FAN =
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN;
constexpr auto PRIMITIVE_TOPOLOGY_TRIANGLE_LIST =
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
constexpr auto PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY =
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY;
constexpr auto PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP =
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP;
constexpr auto PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY =
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY;
constexpr auto QUERY_CONTROL_PRECISE_BIT = VK_QUERY_CONTROL_PRECISE_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT =
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT =
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT =
    VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT =
    VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT =
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT =
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT =
    VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT =
    VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT;
constexpr auto
    QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT =
        VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT;
constexpr auto
    QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT =
        VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT;
constexpr auto QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT =
    VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT;
constexpr auto QUERY_RESULT_64_BIT = VK_QUERY_RESULT_64_BIT;
constexpr auto QUERY_RESULT_PARTIAL_BIT = VK_QUERY_RESULT_PARTIAL_BIT;
constexpr auto QUERY_RESULT_WAIT_BIT = VK_QUERY_RESULT_WAIT_BIT;
constexpr auto QUERY_RESULT_WITH_AVAILABILITY_BIT =
    VK_QUERY_RESULT_WITH_AVAILABILITY_BIT;
constexpr auto QUERY_TYPE_OCCLUSION = VK_QUERY_TYPE_OCCLUSION;
constexpr auto QUERY_TYPE_PIPELINE_STATISTICS =
    VK_QUERY_TYPE_PIPELINE_STATISTICS;
constexpr auto QUERY_TYPE_TIMESTAMP = VK_QUERY_TYPE_TIMESTAMP;
constexpr auto QUEUE_COMPUTE_BIT = VK_QUEUE_COMPUTE_BIT;
constexpr auto QUEUE_FAMILY_EXTERNAL = VK_QUEUE_FAMILY_EXTERNAL;
constexpr auto QUEUE_FAMILY_EXTERNAL = VK_QUEUE_FAMILY_EXTERNAL;
constexpr auto QUEUE_FAMILY_FOREIGN_EXT = VK_QUEUE_FAMILY_FOREIGN_EXT;
constexpr auto QUEUE_FAMILY_IGNORED = VK_QUEUE_FAMILY_IGNORED;
constexpr auto QUEUE_GLOBAL_PRIORITY_HIGH_EXT =
    VK_QUEUE_GLOBAL_PRIORITY_HIGH_EXT;
constexpr auto QUEUE_GLOBAL_PRIORITY_LOW_EXT = VK_QUEUE_GLOBAL_PRIORITY_LOW_EXT;
constexpr auto QUEUE_GLOBAL_PRIORITY_MEDIUM_EXT =
    VK_QUEUE_GLOBAL_PRIORITY_MEDIUM_EXT;
constexpr auto QUEUE_GLOBAL_PRIORITY_REALTIME_EXT =
    VK_QUEUE_GLOBAL_PRIORITY_REALTIME_EXT;
constexpr auto QUEUE_GRAPHICS_BIT = VK_QUEUE_GRAPHICS_BIT;
constexpr auto QUEUE_SPARSE_BINDING_BIT = VK_QUEUE_SPARSE_BINDING_BIT;
constexpr auto QUEUE_TRANSFER_BIT = VK_QUEUE_TRANSFER_BIT;
constexpr auto RASTERIZATION_ORDER_RELAXED_AMD =
    VK_RASTERIZATION_ORDER_RELAXED_AMD;
constexpr auto RASTERIZATION_ORDER_STRICT_AMD =
    VK_RASTERIZATION_ORDER_STRICT_AMD;
constexpr auto REMAINING_ARRAY_LAYERS = VK_REMAINING_ARRAY_LAYERS;
constexpr auto REMAINING_MIP_LEVELS = VK_REMAINING_MIP_LEVELS;
constexpr auto SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER =
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;
constexpr auto SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE =
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
constexpr auto SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT =
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT;
constexpr auto SAMPLER_ADDRESS_MODE_REPEAT = VK_SAMPLER_ADDRESS_MODE_REPEAT;
constexpr auto SAMPLER_MIPMAP_MODE_LINEAR = VK_SAMPLER_MIPMAP_MODE_LINEAR;
constexpr auto SAMPLER_MIPMAP_MODE_NEAREST = VK_SAMPLER_MIPMAP_MODE_NEAREST;
constexpr auto SAMPLER_REDUCTION_MODE_MAX_EXT =
    VK_SAMPLER_REDUCTION_MODE_MAX_EXT;
constexpr auto SAMPLER_REDUCTION_MODE_MIN_EXT =
    VK_SAMPLER_REDUCTION_MODE_MIN_EXT;
constexpr auto SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE_EXT =
    VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE_EXT;
constexpr auto SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY =
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY;
constexpr auto SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020 =
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020;
constexpr auto SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601 =
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601;
constexpr auto SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709 =
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709;
constexpr auto SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY =
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY;
constexpr auto SAMPLER_YCBCR_RANGE_ITU_FULL = VK_SAMPLER_YCBCR_RANGE_ITU_FULL;
constexpr auto SAMPLER_YCBCR_RANGE_ITU_NARROW =
    VK_SAMPLER_YCBCR_RANGE_ITU_NARROW;
constexpr auto SAMPLE_COUNT_16_BIT = VK_SAMPLE_COUNT_16_BIT;
constexpr auto SAMPLE_COUNT_1_BIT = VK_SAMPLE_COUNT_1_BIT;
constexpr auto SAMPLE_COUNT_2_BIT = VK_SAMPLE_COUNT_2_BIT;
constexpr auto SAMPLE_COUNT_32_BIT = VK_SAMPLE_COUNT_32_BIT;
constexpr auto SAMPLE_COUNT_4_BIT = VK_SAMPLE_COUNT_4_BIT;
constexpr auto SAMPLE_COUNT_64_BIT = VK_SAMPLE_COUNT_64_BIT;
constexpr auto SAMPLE_COUNT_8_BIT = VK_SAMPLE_COUNT_8_BIT;
constexpr auto SEMAPHORE_IMPORT_TEMPORARY_BIT =
    VK_SEMAPHORE_IMPORT_TEMPORARY_BIT;
constexpr auto SHADER_INFO_TYPE_BINARY_AMD = VK_SHADER_INFO_TYPE_BINARY_AMD;
constexpr auto SHADER_INFO_TYPE_DISASSEMBLY_AMD =
    VK_SHADER_INFO_TYPE_DISASSEMBLY_AMD;
constexpr auto SHADER_INFO_TYPE_STATISTICS_AMD =
    VK_SHADER_INFO_TYPE_STATISTICS_AMD;
constexpr auto SHADER_STAGE_ALL = VK_SHADER_STAGE_ALL;
constexpr auto SHADER_STAGE_ALL_GRAPHICS = VK_SHADER_STAGE_ALL_GRAPHICS;
constexpr auto SHADER_STAGE_COMPUTE_BIT = VK_SHADER_STAGE_COMPUTE_BIT;
constexpr auto SHADER_STAGE_FRAGMENT_BIT = VK_SHADER_STAGE_FRAGMENT_BIT;
constexpr auto SHADER_STAGE_GEOMETRY_BIT = VK_SHADER_STAGE_GEOMETRY_BIT;
constexpr auto SHADER_STAGE_TESSELLATION_CONTROL_BIT =
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT;
constexpr auto SHADER_STAGE_TESSELLATION_EVALUATION_BIT =
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT;
constexpr auto SHADER_STAGE_VERTEX_BIT = VK_SHADER_STAGE_VERTEX_BIT;
constexpr auto SHARING_MODE_CONCURRENT = VK_SHARING_MODE_CONCURRENT;
constexpr auto SHARING_MODE_EXCLUSIVE = VK_SHARING_MODE_EXCLUSIVE;
constexpr auto SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT =
    VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT;
constexpr auto SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT =
    VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT;
constexpr auto SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT =
    VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT;
constexpr auto SPARSE_MEMORY_BIND_METADATA_BIT =
    VK_SPARSE_MEMORY_BIND_METADATA_BIT;
constexpr auto STENCIL_FACE_BACK_BIT = VK_STENCIL_FACE_BACK_BIT;
constexpr auto STENCIL_FACE_FRONT_BIT = VK_STENCIL_FACE_FRONT_BIT;
constexpr auto STENCIL_FRONT_AND_BACK = VK_STENCIL_FRONT_AND_BACK;
constexpr auto STENCIL_OP_DECREMENT_AND_CLAMP =
    VK_STENCIL_OP_DECREMENT_AND_CLAMP;
constexpr auto STENCIL_OP_DECREMENT_AND_WRAP = VK_STENCIL_OP_DECREMENT_AND_WRAP;
constexpr auto STENCIL_OP_INCREMENT_AND_CLAMP =
    VK_STENCIL_OP_INCREMENT_AND_CLAMP;
constexpr auto STENCIL_OP_INCREMENT_AND_WRAP = VK_STENCIL_OP_INCREMENT_AND_WRAP;
constexpr auto STENCIL_OP_INVERT = VK_STENCIL_OP_INVERT;
constexpr auto STENCIL_OP_KEEP = VK_STENCIL_OP_KEEP;
constexpr auto STENCIL_OP_REPLACE = VK_STENCIL_OP_REPLACE;
constexpr auto STENCIL_OP_ZERO = VK_STENCIL_OP_ZERO;
constexpr auto STRUCTURE_TYPE_APPLICATION_INFO =
    VK_STRUCTURE_TYPE_APPLICATION_INFO;
constexpr auto STRUCTURE_TYPE_BIND_SPARSE_INFO =
    VK_STRUCTURE_TYPE_BIND_SPARSE_INFO;
constexpr auto STRUCTURE_TYPE_BUFFER_CREATE_INFO =
    VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER =
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
constexpr auto STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO =
    VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO =
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
constexpr auto STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO =
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
constexpr auto STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO =
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO;
constexpr auto STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO =
    VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO =
    VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_COPY_DESCRIPTOR_SET =
    VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET;
constexpr auto STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO =
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO =
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
constexpr auto STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO =
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_DEVICE_CREATE_INFO =
    VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO =
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_EVENT_CREATE_INFO =
    VK_STRUCTURE_TYPE_EVENT_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_FENCE_CREATE_INFO =
    VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO =
    VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO =
    VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_IMAGE_CREATE_INFO =
    VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER =
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
constexpr auto STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO =
    VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_INSTANCE_CREATE_INFO =
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO =
    VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO =
    VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_MAPPED_MEMORY_RANGE =
    VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE;
constexpr auto STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO =
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
constexpr auto STRUCTURE_TYPE_MEMORY_BARRIER = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
constexpr auto STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO =
    VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO =
    VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO =
    VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
constexpr auto STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO =
    VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_SAMPLER_CREATE_INFO =
    VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO =
    VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO =
    VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
constexpr auto STRUCTURE_TYPE_SUBMIT_INFO = VK_STRUCTURE_TYPE_SUBMIT_INFO;
constexpr auto STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET =
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
constexpr auto SUBGROUP_FEATURE_ARITHMETIC_BIT =
    VK_SUBGROUP_FEATURE_ARITHMETIC_BIT;
constexpr auto SUBGROUP_FEATURE_BALLOT_BIT = VK_SUBGROUP_FEATURE_BALLOT_BIT;
constexpr auto SUBGROUP_FEATURE_BASIC_BIT = VK_SUBGROUP_FEATURE_BASIC_BIT;
constexpr auto SUBGROUP_FEATURE_CLUSTERED_BIT =
    VK_SUBGROUP_FEATURE_CLUSTERED_BIT;
constexpr auto SUBGROUP_FEATURE_QUAD_BIT = VK_SUBGROUP_FEATURE_QUAD_BIT;
constexpr auto SUBGROUP_FEATURE_SHUFFLE_BIT = VK_SUBGROUP_FEATURE_SHUFFLE_BIT;
constexpr auto SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT =
    VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT;
constexpr auto SUBGROUP_FEATURE_VOTE_BIT = VK_SUBGROUP_FEATURE_VOTE_BIT;
constexpr auto SUBPASS_CONTENTS_INLINE = VK_SUBPASS_CONTENTS_INLINE;
constexpr auto SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS =
    VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS;
constexpr auto SUBPASS_EXTERNAL = VK_SUBPASS_EXTERNAL;
constexpr auto SUCCESS = VK_SUCCESS;
constexpr auto SURFACE_COUNTER_VBLANK_EXT = VK_SURFACE_COUNTER_VBLANK_EXT;
constexpr auto SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR =
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR =
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR =
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR =
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_IDENTITY_BIT_KHR =
    VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_INHERIT_BIT_KHR =
    VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_ROTATE_180_BIT_KHR =
    VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_ROTATE_270_BIT_KHR =
    VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR;
constexpr auto SURFACE_TRANSFORM_ROTATE_90_BIT_KHR =
    VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR;
constexpr auto SYSTEM_ALLOCATION_SCOPE_CACHE = VK_SYSTEM_ALLOCATION_SCOPE_CACHE;
constexpr auto SYSTEM_ALLOCATION_SCOPE_COMMAND =
    VK_SYSTEM_ALLOCATION_SCOPE_COMMAND;
constexpr auto SYSTEM_ALLOCATION_SCOPE_DEVICE =
    VK_SYSTEM_ALLOCATION_SCOPE_DEVICE;
constexpr auto SYSTEM_ALLOCATION_SCOPE_INSTANCE =
    VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE;
constexpr auto SYSTEM_ALLOCATION_SCOPE_OBJECT =
    VK_SYSTEM_ALLOCATION_SCOPE_OBJECT;
constexpr auto TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT =
    VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT;
constexpr auto TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT =
    VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT;
constexpr auto TIMEOUT = VK_TIMEOUT;
constexpr auto TRUE = VK_TRUE;
constexpr auto UUID_SIZE = VK_UUID_SIZE;
constexpr auto VALIDATION_CACHE_HEADER_VERSION_ONE_EXT =
    VK_VALIDATION_CACHE_HEADER_VERSION_ONE_EXT;
constexpr auto VALIDATION_CHECK_ALL_EXT = VK_VALIDATION_CHECK_ALL_EXT;
constexpr auto VALIDATION_CHECK_SHADERS_EXT = VK_VALIDATION_CHECK_SHADERS_EXT;
constexpr auto VENDOR_ID_KAZAN = VK_VENDOR_ID_KAZAN;
constexpr auto VENDOR_ID_VIV = VK_VENDOR_ID_VIV;
constexpr auto VENDOR_ID_VSI = VK_VENDOR_ID_VSI;
constexpr auto VERTEX_INPUT_RATE_INSTANCE = VK_VERTEX_INPUT_RATE_INSTANCE;
constexpr auto VERTEX_INPUT_RATE_VERTEX = VK_VERTEX_INPUT_RATE_VERTEX;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV;
constexpr auto VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV =
    VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV;
constexpr auto WHOLE_SIZE = VK_WHOLE_SIZE;
{ /*struct*/
  using x = VkAcquireNextImageInfoKHR;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAllocationCallbacks;
  x* y;
  (void)y;
}
#ifdef VK_USE_PLATFORM_ANDROID_KHR
{ /*struct*/
  using x = VkAndroidHardwareBufferFormatPropertiesANDROID;
  x* y;
  (void)y;
}
#endif
#ifdef VK_USE_PLATFORM_ANDROID_KHR
{ /*struct*/
  using x = VkAndroidHardwareBufferPropertiesANDROID;
  x* y;
  (void)y;
}
#endif
#ifdef VK_USE_PLATFORM_ANDROID_KHR
{ /*struct*/
  using x = VkAndroidHardwareBufferUsageANDROID;
  x* y;
  (void)y;
}
#endif
#ifdef VK_USE_PLATFORM_ANDROID_KHR
{ /*struct*/
  using x = VkAndroidSurfaceCreateInfoKHR;
  x* y;
  (void)y;
}
#endif
{ /*struct*/
  using x = VkApplicationInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAttachmentDescription;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAttachmentDescription2KHR;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAttachmentReference;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAttachmentReference2KHR;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkAttachmentSampleLocationsEXT;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBaseInStructure;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBaseOutStructure;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindBufferMemoryDeviceGroupInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindBufferMemoryDeviceGroupInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindBufferMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindBufferMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImageMemoryDeviceGroupInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImageMemoryDeviceGroupInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImageMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImageMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImageMemorySwapchainInfoKHR;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImagePlaneMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindImagePlaneMemoryInfo;
  x* y;
  (void)y;
}
{ /*struct*/
  using x = VkBindSparseInfo;
  x* y;
  (void)y;
}
using