package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file",
    hdrs = [
       "file.h",
    ],
)

cc_library(
    name = "scanner",
    srcs = [
        "scanner.h",
    ],
)

cc_library(
    name = "parser",
    srcs = [
        "parser.h",
    ],
)

cc_library(
    name = "json",
    srcs = [
        "json.h",
    ],
)
