package(default_visibility = ["//visibility:public"])

cc_library(
    name = "spock",
    hdrs = [
        "Engine.h",
        "Instance.h",
        "PhysicalDevice.h",
        "Surface.h",
        "Utils.h",
        "Version.h",
        "Window.h",
    ],
    srcs = [
    	"ExtraDefs.cc",
    ],
)